config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from catalog.apps import CatalogConfig
app_name = CatalogConfig.name

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserConfirmationSentView, UserConfirmEmailView, \
    UserConfirmedView, UserResetView, UserResetDoneView, UserResetConfirmView, UserResetCompleteView, generate_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('confirm_your_email/', UserConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', UserConfirmedView.as_view(), name='email_confirmed'),

    path('password_reset/', UserResetView.as_view(), name='password_reset'),
    path('password_reset/done/', UserResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', UserResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', UserResetCompleteView.as_view(), name='password_reset_complete'),

    path("password_reset/update_password", generate_password, name="generate_password"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='Email')
    phone = models.CharField(max_length=30, verbose_name='Phone', **NULLABLE)
    country = models.CharField(max_length=100, verbose_name='Country', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from users.models import User
from catalog.forms import StyleFormMixin


class UserForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

users/views.py
from django.contrib.auth.views import LoginView as BaseLogin
from django.contrib.auth.views import LogoutView as BaseLogout
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes
from django.views.generic import CreateView, TemplateView, UpdateView
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.shortcuts import redirect, render
from django.contrib.auth import login
from django.views import View

from users.forms import UserForm
from users.models import User

from catalog.utils import sendmail
from users.utils import password_generator

import config.settings
import random


class TitleMixin(object):
    title = None


class LoginView(TitleMixin, BaseLogin):
    template_name = 'users/login.html'
    title = 'Логин'


class LogoutView(BaseLogout):
    pass


class RegisterView(TitleMixin, CreateView):
    model = User
    form_class = UserForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('catalog:product_list')
    title = 'Регистрация'

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        user.save()

        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        activation_url = reverse_lazy('users:confirm_email', kwargs={'uidb64': uid, 'token': token})
        current_site = config.settings.SITE_NAME

        sendmail(
            user.email,
            "Регистрация на сайте",
            f"Подтвердите свой e-mail адрес: http://{current_site}{activation_url}"
        )
        return redirect('users:email_confirmation_sent')


class UserConfirmationSentView(PasswordResetDoneView):
    template_name = "users/registration_sent.html"


class UserConfirmEmailView(View):

    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('users:email_confirmed')


class UserConfirmedView(TitleMixin, TemplateView):
    template_name = 'users/registration_confirm.html'
    title = "Почта активирована!"


class UserResetView(PasswordResetView):
    template_name = "users/reset/password_reset_form.html"
    email_template_name = "users/reset/password_reset_email.html"
    success_url = reverse_lazy('users:password_reset_done')


class UserResetDoneView(PasswordResetDoneView):
    template_name = "users/reset/password_reset_done.html"


class UserResetConfirmView(PasswordResetConfirmView):
    template_name = "users/reset/password_reset_confirm.html"
    success_url = reverse_lazy("users:password_reset_complete")


class UserResetCompleteView(PasswordResetCompleteView):
    template_name = "users/reset/password_reset_complete.html"


def generate_password(request):
    new_password = password_generator()
    sendmail(request.user.email, "Замена пароля на сайте Skyfarm", new_password)
    request.user.set_password(new_password)
    request.user.save()

    return render(request, 'users/reset/reset_complete.html')

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-6">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            Войти
                        </button>
                        <a href="{% url 'users:password_reset' %}"
                           class="w-100 btn btn-lg btn-outline-primary">Забыли пароль?</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'catalog/base.html' %}

{% block content %}

<h1>Восстановление пароля</h1>
{% if validlink %}
<p>Ваш новый пароль был выслан вам на почту</p>
{% else %}
<p>Ссылка для сброса пароля была недействительной, возможно, потому, что она уже
была использована. Пожалуйста, запросите сброс нового пароля.</p>
{% endif %}

{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-6">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            Регистрация
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/registration_confirm.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Почта подтверждена!</h4>
    <p>Ваша почта была подтверждена</p>
</div>

{% endblock %}

users/templates/users/registration_sent.html
{% extends 'catalog/base.html' %}

{% block content %}
<h3>Подтвердите вашу почту</h3>
<p>Мы отправили вам на почту письмо с инструкциями.</p>

{% endblock %}