catalog/urls.py
from django.urls import path
from catalog.views import ProductListView, ProductDetailView, ProductCreateView, ProductDeleteView, ProductUpdateView, \
    contacts, \
    BlogListView, BlogCreateView, BlogUpdateView, BlogDeleteView, BlogDetailView, ResetPassword

from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='view'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/edit/<int:pk>/', ProductUpdateView.as_view(), name='product_edit'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),

    path("password_reset/generate_password", ResetPassword.as_view(), name="generate_password"),

    path('contacts/', contacts),

    path('blog/', BlogListView.as_view(), name='blogs'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/edit/<slug:slug>', BlogUpdateView.as_view(), name='blog_edit'),
    path('blog/<slug:slug>', BlogDetailView.as_view(), name='blog'),
    path('blog/delete/<slug:slug>', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from catalog.apps import CatalogConfig
app_name = CatalogConfig.name

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserConfirmationSentView, UserConfirmEmailView, \
    UserConfirmedView, UserResetView, UserResetDoneView, UserResetConfirmView, UserResetCompleteView, generate_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('confirm_your_email/', UserConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', UserConfirmedView.as_view(), name='email_confirmed'),

    path('password_reset/', UserResetView.as_view(), name='password_reset'),
    path('password_reset/done/', UserResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', UserResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', UserResetCompleteView.as_view(), name='password_reset_complete'),

    path("password_reset/update_password", generate_password, name="generate_password"),
]

catalog/models.py
from django.db import models
from config import settings

NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.CharField(max_length=100, verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='images/', unique=True, **NULLABLE, verbose_name='Изображение')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена')
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    last_change = models.DateField(auto_now=True, verbose_name='Последнее изменение')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Owner')

    def __str__(self):
        return f'{self.name} ({self.category})'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    @property
    def active_version(self):
        return self.version_set.last()


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, **NULLABLE, verbose_name='slug')
    body = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='images/', **NULLABLE, verbose_name='Изображение')
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Признак публикации')
    view_count = models.IntegerField(default=0, verbose_name='Просмотры')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    ver_num = models.IntegerField(verbose_name='Версия')
    ver_name = models.CharField(max_length=100, verbose_name='Название версии')
    is_published = models.BooleanField(default=True, verbose_name='Признак версии')

    def __str__(self):
        return f'Версия {self.ver_num} | {self.ver_name}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    banned_words = ['казино', 'криптовалют', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        fields = ('name', 'description', 'image', 'category', 'price',)

    def clean_name(self):
        cleaned_data = str(self.cleaned_data['name'])

        for word in self.banned_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError('В названии товара фигурируют запрещенные слова')

        return cleaned_data

    def clean_description(self):
        cleaned_data = str(self.cleaned_data['description'])

        for word in self.banned_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError('В описании товара фигурируют запрещенные слова')

        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = "__all__"

catalog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify
from django.forms import inlineformset_factory
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin

from catalog.models import Product, Blog, Version
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from catalog.forms import ProductForm, VersionForm


# Create your views here.
class ProductListView(ListView):
    model = Product


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    login_url = '../../users/'
    redirect_field_name = 'redirect_to'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["Title"] = "Product Information"
        context["product"] = self.get_object()
        product_version = self.get_object()

        context["product_version"] = product_version.active_version
        return context

    def get_object(self, queryset=None):
        if self.object.owner != self.request.user:
            raise PermissionDenied('Вы не владелец данного продукта.')

        else:
            return self.object


class ProductCreateView(LoginRequiredMixin, CreateView):
    login_url = '../../users/'
    redirect_field_name = 'redirect_to'
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:view',)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["Title"] = "Update Product"
        SubjectFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)

        if self.request.method == "POST":
            context["formset"] = SubjectFormset(self.request.POST)
        else:
            context["formset"] = SubjectFormset()
        return context


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '../../users/'
    redirect_field_name = 'redirect_to'
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:view')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["Title"] = "Update Product"

        SubjectFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == "POST":
            context["formset"] = SubjectFormset(self.request.POST, instance=self.object)
        else:
            context["formset"] = SubjectFormset(instance=self.object)

        return context

    def get_object(self, queryset=None):
        if self.object.owner != self.request.user:
            raise PermissionDenied('Вы не владелец данного продукта.')

        else:
            return self.object

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()

        if formset.is_valid():
            versions = Version.objects.all()

            for version in versions:
                version.is_published = False
                version.save()

            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '../../users/'
    redirect_field_name = 'redirect_to'
    model = Product
    success_url = reverse_lazy('catalog:view')

    def get_object(self, queryset=None):
        if self.object.owner != self.request.user:
            raise PermissionDenied('Вы не владелец данного продукта.')

        else:
            return self.object


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'Вам письмо, вот. От {name} ({phone}): \n{message}')
    return render(request, 'catalog/contacts.html')


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        """if is_published == True"""
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)

        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        """view count"""
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()

        return self.object


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'body', 'preview',)
    success_url = reverse_lazy('catalog:blogs')

    def form_valid(self, form):
        """slugify"""
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'body', 'preview',)
    #success_url = reverse_lazy('catalog:blogs')

    def form_valid(self, form):
        """slugify"""
        if form.is_valid():
            edited_post = form.save()
            edited_post.slug = slugify(edited_post.title)

        return super().form_valid(form)

    def get_success_url(self):
        """Перенаправление на обновленный пост"""
        return reverse('catalog:blog', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('catalog:blogs')


class ResetPassword(ListView):
    model = Product
    template_name = 'catalog/reset_password.html'

catalog/templates/catalog/base.html
<load static>
    <!doctype html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Skyfarm</title>
        <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <h5 class="my-0 mr-md-auto font-weight-normal">Skyfarm</h5>
        <nav class="ms-5">
            <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
            <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
            {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выход</a>
            {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Вход</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
            {% endif %}
        </nav>
    </div>

    {% block content %}
    {% endblock %}

    <div class="container">
        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col-12 col-md">
                    Skyfarm
                    <small class="d-block mb-3 text-muted">&copy; 2023</small>
                </div>
                <div class="col-6 col-md">
                    <h5>Категории</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Рассылки</a></li>
                        <li><a class="text-muted" href="#">Телеграм боты</a></li>
                        <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                        <li><a class="text-muted" href="#">Веб-приложения</a></li>
                        <li><a class="text-muted" href="#">Микросервисы</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>Дополнительно</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="/blog/">Мы пишем</a></li>
                        <li><a class="text-muted" href= "{% url 'catalog:generate_password' %}">Обновление пароля</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>О нас</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </div>

    <script src="/static/js/bootstrap.bundle.min.js"></script>
    </body>
    </html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-6">
    <div class="row">
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить пост {{ blog.title }}?</p>
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                        <a href="{% url 'catalog:blogs' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load product_tags %}

{% block content %}
What?: {{ blog.title }}<p>
Slug: {{ blog.slug }}<p>
Text: {{ blog.body }}<p>
Views: {{ blog.view_count }}<p>
<img src="{% mediapath_tag blog.preview %}" width="300"/>
{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-6">
    <div class="row">
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if blog %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}
{% load product_tags %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <p class="lead">Skyfarm.zen - все про зелень</p>
</div>

<div class="col-6 mb-5">
    <a href="{% url 'catalog:blog_create' %}" class="w-30 btn btn-lg btn-primary">Создать</a>
</div>

<div class="row text-center">

    {% for blog in blog_list %}

    <div class="col-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ blog.title }}</h4>
            </div>
            <div class="card-body">
                <img src="{% mediapath_tag blog.preview %}" width="300"/>
                <a href="{% url 'catalog:blog' blog.slug %}"
                   class="w-100 btn btn-lg btn-outline-primary">Читать</a>
                <a href="{% url 'catalog:blog_edit' blog.slug %}"
                   class="w-100 btn btn-lg btn-outline-primary">Поменять</a>
                <a href="{% url 'catalog:blog_delete' blog.slug %}"
                   class="w-100 btn btn-lg btn-outline-warning">Удалить</a>
            </div>
        </div>
    </div>

    {% endfor %}

</div>

{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Письмо"
                                      required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Удобный сервис рассылок</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ 140</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- Неограниченная лицензия</li>
                        <li>- Поддержка</li>
                        <li>- Установка на сервер</li>
                        <li>- Получение обновлений</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load product_tags %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skyfarm</h1>
    <p class="lead">Skyfarm - это отличный выбор для ресторанов, кафе и частных покупателей, желающих в полной мере
        погрузиться в мир качественных продуктов растительного происхождения</p>
</div>

<div class="row text-center">

    {% for product in product_list %}

    <div class="col-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">{{ product.price }}₽</h1>
                <img src="{% mediapath_tag product.image %}" width="300"/>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>{{ product.description|slice:'100' }}</li>
                </ul>
                <a href="{% url 'product_cart' product.id %}" class="w-100 btn btn-lg btn-outline-primary">Show</a>
            </div>
        </div>
    </div>

    {% endfor %}

</div>

{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-6">
    <div class="row">
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить товар {{ product.title }}?</p>
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                        <a href="{% url 'catalog:view' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load product_tags %}

{% block content %}
NAME: {{ product.name }}<p>
PRICE: {{ product.price }}<p>
DESCRIPTION: {{ product.description }}<p>
ADDITIONAL INFORMATION:
{% if product_version %}
    {{ product_version }}
{% else %}
    Версий продукта нет.
{% endif %}<p>
<img src="{% mediapath_tag product.image %}" width="300"/>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="row">

                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if product %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-6">
            <div class="row">

                <div class="card">
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% endfor %}
                    </div>
                </div>

            </div>
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load product_tags %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skyfarm</h1>
    <p class="lead">Skyfarm - это отличный выбор для ресторанов, кафе и частных покупателей, желающих в полной мере
        погрузиться в мир качественных продуктов растительного происхождения</p>
</div>

<div class="col-6 mb-5">
    <a href="{% url 'catalog:product_create' %}" class="w-30 btn btn-lg btn-primary">Создать</a>
</div>

<div class="row text-center">

    {% for product in product_list %}

    <div class="col-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">{{ product.price }}₽</h1>
                <img src="{% mediapath_tag product.image %}" width="300"/>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>{{ product.description|slice:'100' }}</li>
                </ul>
                <a href="{% url 'catalog:product' product.pk %}"
                   class="w-100 btn btn-lg btn-outline-primary">Показать</a>
                <a href="{% url 'catalog:product_edit' product.pk %}"
                   class="w-100 btn btn-lg btn-outline-primary">Изменить</a>
                <a href="{% url 'catalog:product_delete' product.pk %}"
                   class="w-100 btn btn-lg btn-outline-warning">Удалить</a>
            </div>
        </div>
    </div>

    {% endfor %}

</div>

{% endblock %}

catalog/templates/catalog/reset_password.html
{% extends 'catalog/base.html' %}
{% block content %}

<h2>Восстановление пароля</h2>
<p>Вы уверены, что хотите изменить ваш пароль?</p>

<a href="{% url 'users:generate_password' %}"
   class="w-100 btn btn-lg btn-outline-primary">Изменить пароль</a>

{% endblock %}